### ISSUE TITLE
app unistalls It self after update

### ISSUE THREAD

**Issue by F3niIxX** [irixaligned/duckstation-uwp#1]
### Game details

0

### Description of the issue/bug

when i open the app It unistalls It self im using Xbox one S..... the error says u haver to wait "app is ready to start" before..... and the app Just vanish

old version Works fine b4 2024-03-09

### Steps to reproduce

install

open

unistall automaticaly

### Software and hardware information

one s dev mode

### DuckStation version

 2024-03-09

### DuckStation rendering backend

Software

### DuckStation controller backend, drivers and wrappers

0

**Comment by irixaligned** [comment]
did you actually try more than once before making this issue

**Comment by F3niIxX** [comment]
3x times , even tryed update and clean install ... Same

**Comment by irixaligned** [comment]
that's Xbox devmode jank; it's known for doing that, particularly on Xbox Ones and is unrelated to my emulator. I haven't owned a One in forever and have only done development on a Series so I am incapable of assisting with this (if it even is fixable). Your best bet is asking in the Discord, they'll help you gladly there. I'm gonna close this for now but if the issue does happen to seem to be related to my emulator somehow I'll happily reopen it later.
